#!/usr/bin/env bash
# Convert Android SDK Demo — emulator setup helper.
#
# Installs the Google APIs system image and creates an AVD ready to run
# the demo from the command line, bypassing Android Studio's SDK Manager
# and Device Manager UI. See ../README.md "Run the demo in Android Studio"
# for the system-image + standalone-window requirements rationale.
#
# Usage (run from demo/android-app/):
#     ./scripts/setup-emulator.sh
#
# Idempotent — re-running is safe: the system-image install is skipped
# when the package is already present; the AVD is left alone if it
# already exists under the chosen name.
#
# Supported hosts: macOS (Apple Silicon + Intel) and Linux.
# Windows users: follow the Android Studio UI steps in README.md.

set -euo pipefail

AVD_NAME="Convert_Demo_API_34"
API_LEVEL="34"
HARDWARE_PROFILE="pixel_3a"

# --- Detect the Android SDK -----------------------------------------------
ANDROID_HOME="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Library/Android/sdk}}"
if [[ ! -d "$ANDROID_HOME" ]]; then
    echo "Error: Android SDK not found at $ANDROID_HOME" >&2
    echo "Set the ANDROID_HOME environment variable, or install Android Studio first." >&2
    exit 1
fi

# --- Detect host CPU arch -------------------------------------------------
case "$(uname -m)" in
    arm64|aarch64) ABI="arm64-v8a" ;;
    x86_64|amd64)  ABI="x86_64" ;;
    *)
        echo "Error: unsupported host architecture '$(uname -m)'." >&2
        echo "Run this script on macOS (Apple Silicon or Intel) or Linux x86_64." >&2
        exit 1
        ;;
esac

# --- Locate sdkmanager + avdmanager --------------------------------------
SDKMANAGER="$(find "$ANDROID_HOME/cmdline-tools" -name sdkmanager -type f 2>/dev/null | head -1 || true)"
AVDMANAGER="$(find "$ANDROID_HOME/cmdline-tools" -name avdmanager -type f 2>/dev/null | head -1 || true)"
if [[ -z "$SDKMANAGER" || ! -x "$SDKMANAGER" ]] || [[ -z "$AVDMANAGER" || ! -x "$AVDMANAGER" ]]; then
    echo "Error: sdkmanager / avdmanager not found under $ANDROID_HOME/cmdline-tools/" >&2
    echo "Open Android Studio → SDK Manager → SDK Tools tab → tick" >&2
    echo "  'Android SDK Command-line Tools (latest)' → Apply." >&2
    exit 1
fi

# --- Install the Google APIs system image --------------------------------
PACKAGE="system-images;android-${API_LEVEL};google_apis;${ABI}"
echo "==> Installing ${PACKAGE} (skipped if already present; first install ~1.5 GB)..."
yes | "$SDKMANAGER" --install "$PACKAGE" >/dev/null

# --- Create the AVD -------------------------------------------------------
if "$AVDMANAGER" list avd 2>/dev/null | grep -q "Name: ${AVD_NAME}"; then
    echo "==> AVD '${AVD_NAME}' already exists — skipping creation."
else
    echo "==> Creating AVD '${AVD_NAME}' on the ${HARDWARE_PROFILE} hardware profile..."
    # `no` answers the "create custom hardware profile?" prompt; we want
    # the bundled hardware profile, not a custom one.
    echo "no" | "$AVDMANAGER" create avd \
        --name "$AVD_NAME" \
        --package "$PACKAGE" \
        --device "$HARDWARE_PROFILE" \
        --force >/dev/null
fi

# --- Done -----------------------------------------------------------------
EMULATOR_BIN="$ANDROID_HOME/emulator/emulator"
cat <<EOF

==> Done.

To launch the emulator from the CLI (standalone window — fully delivers
mouse clicks and multi-touch gestures, unlike the embedded "Running
Devices" tool window):

    "${EMULATOR_BIN}" -avd ${AVD_NAME} &

Then in Android Studio:
  - Run-config dropdown is already set to 'app' (auto-generated by AGP)
  - Device dropdown → select '${AVD_NAME}'
  - Click the green ▶ Run button

If you prefer to launch via Android Studio's Device Manager instead,
the same AVD is selectable there. Either way, do not run the emulator
embedded in the "Running Devices" tool window — multi-touch gestures
won't reach the app (per Android Studio's own troubleshooting docs).
EOF
