/*
 * Convert Android SDK — core/port
 * Copyright (c) 2026 Convert Insights, Inc.
 * License: Apache-2.0
 */
package com.convert.sdk.core.port

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

/**
 * Covers the default / bundled artifacts on the port interfaces so that
 * coverage accurately reflects the shipped surface:
 *
 *  * [Logger.NoOp] — the anonymous no-op implementation the SDK falls back on
 *    until Story 2.2 wires a Logcat-backed adapter. Every method is trivial
 *    but must still be executed at least once for Kover to attribute lines.
 *  * [HttpClient.HttpResponse] — a pure data class used as the transport
 *    envelope; exercising the constructor + accessors gives coverage for
 *    the generated component/equals/hashCode bytecode.
 */
internal class PortDefaultsTest {

    @Test
    fun `Logger NoOp accepts every severity without throwing`() {
        val logger: Logger = Logger.NoOp
        logger.debug("debug message")
        logger.info("info message")
        logger.warn("warn with no cause")
        logger.warn("warn with cause", IllegalStateException("boom"))
        logger.error("error with no cause")
        logger.error("error with cause", RuntimeException("nope"))
        // The NoOp is a singleton — accessing it twice must yield the same
        // instance so the SDK's default-logger wiring can compare by identity.
        assertEquals(logger, Logger.NoOp)
    }

    @Test
    fun `HttpResponse round-trips its constructor arguments`() {
        val headers = mapOf("content-type" to "application/json", "x-trace-id" to "abc")
        val response = HttpClient.HttpResponse(
            statusCode = 204,
            body = "",
            headers = headers,
        )

        assertEquals(204, response.statusCode)
        assertEquals("", response.body)
        assertEquals(headers, response.headers)

        // Data class equality + copy behaviour exercises generated bytecode.
        val copy = response.copy(statusCode = 200)
        assertEquals(200, copy.statusCode)
        assertEquals(response.body, copy.body)
        assertEquals(response, response.copy())
        assertNotNull(response.toString())
        assertEquals(response.hashCode(), response.copy().hashCode())
    }
}
